### PR TITLE
Require user to be in team

### LINKED ISSUE #44: Show useful message if not in team
App users need to be a member of the [STOP-AD_Reviewers team](https://www.synapse.org/#!Team:3403721). If you're not in the team, you won't have access to the Synapse project and the app will fail when it tries to get the reviews stored on Synapse. Prevent this the same way we do in dccvalidator, by showing a modal indicating that you need to join the team.

### PR DESCRIPTION
**Pull request by karawoo**
Fixes #44 

Not sure what is the best way to handle the case when the user isn't certified. It might be good to still let them view data, they just won't be able to submit reviews. So we could prevent clicking the submit button if they're not certified? @Aryllen what do you think?

### CODE REVIEW

**Comment by Aryllen** [comment]
Changing permissions in this specific app for certified users seems a little arbitrary unless not being certified would actually stop them from being able to do something the app is trying to do. For example, if not being certified would stop the user from being able to edit the comment table, then, yes, we should require them to be certified for that. I was looking at the permissions in the docs and I'm not sure this is the case, though. It looks like they aren't supposed to be able to upload tables, but it doesn't mention if they can add to tables.

Overall, becoming certified is fairly simple and doesn't seem like much of a barrier for limiting who can/cannot comment on submissions, especially since becoming certified is not tied to the specific project. Given that this is a small team, if a person is a part of the team, then I feel like they are expected to be able to use the app in full (provided we don't get some extra requirements to limit full submission comments to certain users in the future).

So that would be my question, can a non-certified user add to a table?

**Comment by karawoo** [comment]
A non-certified user cannot add to the table, that's why we need to add this

**Comment by karawoo** [comment]
This is what they currently see: 

Screen Shot 2020-02-14 at 9 17 35 AM

**Comment by Aryllen** [comment]
Ah, that makes sense, then. I agree, we should let members of the team see the reviews, but block the submit buttons for comments. There should be some notice that pops up or is written as to why they cannot comment, though. Otherwise they may just think the app is broken instead of fixing the problem of not being certified.

**Comment by karawoo** [comment]
> There should be some notice that pops up or is written as to why they cannot comment, though

yes definitely!

**Comment by Aryllen** [comment]
Do you want the certified user part to be a separate issue/PR or add on to this one?

**Comment by karawoo** [comment]
Let's do it separately, I'll open a separate issue too

**Pull request merged**
