### PR TITLE
fix refresh error

### PR DESCRIPTION
**Pull request by j-hendrickson-sage**
This fixes refresh error.

From @brucehoff 

"I think what’s going on here is that when I reload the page I make the Shiny app’ think it’s getting a redirect back from Synapse and it tries to get an access token with the old auth’ code.  The app’ gets a 400 response from Synapse and displays the error message.
[11:48](https://sagebionetworks.slack.com/archives/C03N8UHRACQ/p1656614923834989)
The way to test the theory is to change the app’ so that the auth’ code is not available in the URL bar for ‘replay’."

https://github.com/curso-r/auth0/issues/54#issuecomment-719111543
https://sagebionetworks.jira.com/browse/SWC-5297

### CODE REVIEW

**Review by danlu1 — APPROVED** [review]
Looks good to me!

**Review by BrunoGrandePhD — APPROVED** [review]
🚀

**Comment by brucehoff** [comment]
@j-hendrickson-sage If you want this change deployed to the Shiny Server Pro, kindly let me know.

**Comment by j-hendrickson-sage** [comment]
@brucehoff I set up a ticket which (https://sagebionetworks.jira.com/browse/IT-2021).  The app is ready to be deployed.

**Pull request merged**
