### PR TITLE
More user-friendly app with requested features

### LINKED ISSUE #13: Create user-friendly submission names
Reviewers will want to see something like submitter last name + compound name to identify submissions (however this might not be fully unique). Internally we should use the userid + form data ID to identify submissions, but display the friendlier version to the user. Not sure what to do if they're not unique, maybe add 1, 2, etc.?

### LINKED ISSUE #14: Alias variable names
Replace the variable names with underscores to the versions shown on the STOP-AD site when the user fills out the form.

### LINKED ISSUE #15: Show TRUE/FALSE as yes/no in submissions

### LINKED ISSUE #16: Remove metadata section
The form data contains a metadata section that is not relevant for reviewing; remove it from the list of section options.

### LINKED ISSUE #17: Add tab to search across submissions
Show all submissions (including those that have been accepted and rejected) in a table on a new tab in the app. Each row should be a submission that can be expanded to show the contents of the submission, like we do currently with the reviews table in the "View summarized scores" tab. Search tab will allow free text search across submissions. We will not include the comments or scores in this table for the time being.

### PR DESCRIPTION
**Pull request by Aryllen**
Fixes #13, #14, #15, #16, #17.

Synapse tables:
- `formDataId` column added to both tables. Done in snake-case to match other Synapse uses of this variable. In the app, `formDataId` is called `form_data_id` to match tidyverse variable style. In general, this doesn't seem to cause much of an issue and the lintr yells less. Adding the `formDataId` gives a unique way of referencing submissions, in the event that two submissions have the same composite name (ie. last_name - compound_name).

Overall submissions:
- Makes submissions into a "clean" table with the following columns:
  * `form_data_id`: Unique, number id that designates which submission form a submission is within the Synapse forms database.
  * `submission`: (Not guaranteed to be unique) submission name in the form of last_name - compound_name (fixes #13).
  * `step`: Section name as displayed in STOP-AD forms webform, or the main section of the form if the step is not mapped in the webform (ex: json metadata section is not shown in the webform, but the step will still show metadata as the step name) (fixes #14).
  * `label`: Variable name as displayed in STOP-AD forms webform, or the variable name if the step is not mapped in the webform (ex: json variables route1, route2, etc in the Basic Data step is not mapped in the webform; these are shown in the app as the json variable name, route1, route2, etc) (fixes #14).
  * `response`: The submission response. All TRUE/FALSE responses are changed to Yes/No (fixes #15).

Review tab:
- The `selectInput` for submissions is updated to get a named list of submissions and `form_data_id`s. The backend refers to the submission via the `form_data_id` since this is unique. For example, when checking the Synapse table to see if a review has already been given for a specific submission section and individual, the call has changed from filtering by the submission name to the `form_data_id`. This allows submission names that are not unique to not mess up the table.
- The displayed table only shows the `Label` and `Response` for the submission section. This is partially due to it being redundant to show the submission name and section, and partially due to long label names and responses. By only having these two columns, there is less text wrapping and it looks (subjectively) cleaner.
- Metadata section does not appear in section results (fixes #16).

Panel tab:
- The `selectInput` for submissions is updated to get a named list of submissions and `form_data_id`s. The backend refers to the submission via the `form_data_id` since this is unique.

View all tab (fixes #17):
- Adds tab that displays all submissions in a table, including the submission name, submission id (form_data_id), section, label, and response. Does not display submission metadata sections.
- Table is searchable.
- Table is grouped by submission, form_data_id, and section. If we knew that the submission names would be unique, we could remove the form_data_id column and grouping. Since we don't, we should leave it as is. It does make the table a little annoying to navigate, however.

Misc:
- Updates version.
- Updates lock file to have latest version of synapseforms.
- Moves functions that get and clean/organize submission data table to new file data-gather-clean.R for organization.

This is a large update and was done via several PRs, with the exception of adding user-friendly names and referencing via the `form_data_id`. If this is too much to add at once, we can do PRs to master for the following branches, in order: friendly-variables, edit-logical-to-yes-no, section-bug, all-submission-tab, dev (gets the user-friendly submission names). If it's fine to merge from dev, then we can remove those other branches. dev branch currently deployed on shiny server [here](https://shinypro.synapse.org/users/nkauer/stopadforms/).

### CODE REVIEW

**Comment by karawoo** [comment]
Thanks for all your work on this @Aryllen! I do think it would be a lot easier to review if we could split it up. If you have the separate branches still, would you mind making separate PRs and I will review them in order? Also, could we add the `lastname - compoundname` format submission names to the dropdown in the "View summarized scores" tab as well?

**Comment by Aryllen** [comment]
> I do think it would be a lot easier to review if we could split it up. If you have the separate branches still, would you mind making separate PRs and I will review them in order? 

Sure! I'll get those PRs done shortly.

> Also, could we add the `lastname - compoundname` format submission names to the dropdown in the "View summarized scores" tab as well?

The "View summarized scores" tab is going strictly off the table in Synapse. That section of the app does not have access to the submissions themselves at the moment. If we clean out that table of all the test information, then any new test/real rows we make will have the new submission naming (once the new naming is merged into master). Since the clients probably do not want to see our testing stuff when they finally start using the application, I simply assumed we would clean that out before they had access (and thus "fixing" the naming issue). Does this seem reasonable?

**Comment by Aryllen** [comment]
PRs in order are #32, #33, #34, #25. I did realize that my branches aren't completely separate since I merged the dev branch into them to make sure they worked together (I should have done that differently). It still makes for smaller chunks/updates to look at, however. If there's any questions, please let me know.

**Comment by Aryllen** [comment]
Closing because this is resolved in the PRs mentioned above.

**Pull request closed without merging**
