### PR TITLE
remove python package stick

### PR DESCRIPTION
**Pull request by j-hendrickson-sage**

### CODE REVIEW

**Review by JessterB — CHANGES_REQUESTED** [review]
Something has gone awry here...

It looks like you pushed a change directly to the master branch, somehow bypassing the branch protection rules (which I think you can do as an admin, but you really, really shouldn't).

That push renamed the oauth file to `mod-synapse-oauth.R.bak`, so we no longer have a valid `mod-synapse-oauth.R` file in the master branch.

I see two paths to resolve this:
1. Amend this PR to include both the .R.bak (with versions) and the .R (without versions) copies of the file, and when we merge that PR the master branch should be back in a valid state, and the resulting deploy will test whether the auth error goes away w/o Tom's version changes.

2. Figure out the best way to revert/rollback your inadvertent push to master, then amend this (or put up a new) PR to just remove the pinned versions from the .R (and only) copy of the file, and on merge the resulting deploy will validate that the auth error goes away w/o Tom's changes.

**Comment by j-hendrickson-sage** [comment]
@JessterB This is passing on at least one R-CMD-check operating system.

**Comment by JessterB** [comment]
It looks like the failing step is running with R 4.3.0 (released today per https://www.r-project.org/), which might not be backwards compatible with some of our dependencies. We should probably make sure that we are running a check against the version of R that the app actually uses. I see R 4.2.3 in the shinyapps.io logs from staging.

**Comment by j-hendrickson-sage** [comment]
The R-CMD-check verifies if the latest version of R runs okay which it doesn't.  We may be okay with the app running in a legacy R version.

**Comment by j-hendrickson-sage** [comment]
The app seems to use the latest r version.  We should pin it at 4.2.3, along with pinning all of the packages.

**Review by JessterB — APPROVED** [review]

**Pull request merged**
