### PR TITLE
ALZ-138 bug fix

### PR DESCRIPTION
**Pull request by j-hendrickson-sage**
Introduced mild hack to preserve functionality of pivot_longer function that changed with tidyr update on January 24th, 2023 https://tidyr.tidyverse.org/news/index.html

### CODE REVIEW

**Comment by avanlinden** [comment]
@j-hendrickson-sage This looks alright to me, and if it's passing tests it seems fine. I would recommend adding some quick notes in the pull request comment about any changes you tried to make the updated function work and how they failed, just in case someone needs to come back to this at some point.

**Review by avanlinden — APPROVED** [review]

**Review by andrewelamb — APPROVED** [review]

**Comment by andrewelamb** [comment]
Yep looks good, this is pretty close to what we disscused.

**Comment by j-hendrickson-sage** [comment]
> clinicals
# A tibble: 1 × 1
    `1`
  <dbl>
1  0.67

**Comment by j-hendrickson-sage** [comment]
pivot_longer needs to somehow change this tibble which is not quite what it seems designed for: https://cmdlinetips.com/2020/11/reshape-wide-data-to-tidy-data-with-pivot_longer-tidyr/

**Review by lakikowolfe — APPROVED** [review]
Looks good

**Pull request merged**
